title: Faithful Friends Kennels
email: faithfulfriendskennels@gmail.com
phone: 07800515166
telephone: 01271 269364
short_address: Braunton, EX33 2NQ
description: >
  Faithful Frinds Kennels is a family run, licensed dog boarding kennels located in North
  Devon with over 30 years of experience caring for dogs of all different breeds and ages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://faithfulfriendskennels.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
socials:
  facebook: https://www.facebook.com/faithfulfriendskennels/
  google-plus: https://plus.google.com/+FaithfulfriendskennelsCoUk
collections:
  - testimonials
  - faqs

opening_times:
  mon_sat:
    morning: 10am - 12:30pm
    afternoon: 4:00pm - 5:30pm
  sunday:
    morning: 10am - 12:00pm

prices:
  one_dog: £15
  two_dog: £24
  extra: £10

# Build settings
exclude:
  - node_modules
  - webpack.config.js
  - package.json
  - package-lock.json
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
